#!/bin/sh /etc/rc.common
#
# SPDX-License-Identifier: GPL-2.0-only
#
# shellcheck disable=SC2034 # USE_PROCD/START/STOP are read by /etc/rc.common

USE_PROCD=1
START=96
STOP=10

PROG=/usr/libexec/netifyd-luci/history-collector.sh

start_service() {
	local enabled

	config_load netifyd-luci-history
	config_get_bool enabled main enabled 0
	[ "$enabled" -eq 0 ] && return 0

	mkdir -p /var/run/netifyd-history

	procd_open_instance
	procd_set_param command "$PROG"
	procd_set_param respawn
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

reload_service() {
	stop
	start
}

service_triggers() {
	procd_add_reload_trigger "netifyd-luci-history"
}
